### ISSUE TITLE
Execution speed

### ISSUE THREAD

**Issue by yzhou359** [utlive/MOVIE#1]
Thanks for sharing the code. I'm experiencing a super slow execution speed for MOVIE index (gcc version). It took about ~20 hours to get the result for 800 frames (512x512). It should not be the problem about the RAM since my system has 32G RAM. Is this a normal speed? Is there any other optimized QA metric to evaluate spatial-temporal (or just temporal) perceptual quality? I'm new in this field and would appreciate your answer.

**Comment by JoshuaEbenezer** [comment]
Hi Yang. I've sent you an email to follow up on this. Regarding other QA metrics, you can also check out VBLIINDS, STRRED, SpEED VQA, or ChipQA.

**Comment by yzhou359** [comment]
Thanks, this really helps.
